### ISSUE TITLE
Icons showing as a single pixel

### ISSUE THREAD

**Issue by mat128** [wicketforge/wicketforge#183]
Wicket icons (such as the ones allowing navigation to the component markup file) are showing as a single pixel. See screenshots.

![Screen Shot 2021-10-04 at 7 00 37 PM](https://user-images.githubusercontent.com/234168/135936596-201f9bdc-78c2-4a26-98bc-10126adc0ff5.png)

![Screen Shot 2021-10-04 at 7 20 58 PM](https://user-images.githubusercontent.com/234168/135937310-2bf5e1f0-ab06-4441-a493-7c5538588b50.png)

The issue looks related to the following:

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360005563519-IconLoader-returning-nothing-but-black-pixel-in-2019-2
- https://youtrack.jetbrains.com/issue/IDEA-218876

Affected versions: 6.0.1, 6.0.3.

IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: ParNew, ConcurrentMarkSweep
Memory: 6077M
Cores: 8
Non-Bundled Plugins: com.jetbrains.ChooseRuntime (1.2), name.kropp.intellij.makefile (212.4746.52), WicketForge (6.0.3), org.plugin.dot.id (1.2), com.dmarcotte.handlebars (212.4746.57), pro.bashsupport (2.0.5.212), com.jetbrains.php (212.5284.49), org.jetbrains.plugins.phpstorm-remote-interpreter (212.4746.52), org.jetbrains.plugins.phpstorm-docker (212.4746.52), com.hotswap.agent.plugin (1.3.0), Pythonid (212.5284.44), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7)
Kotlin: 212-1.5.31-release-546-IJ4638.7

**Comment by bamarc** [comment]
The resource-paths were wrong, it will be fixed with the next version. Thank you for the report.
