### ISSUE TITLE
Compatibility with Intellij 2022.2

### ISSUE THREAD

**Issue by bamarc** [wicketforge/wicketforge#186]
TODO: 

- Update JVM Version
- Update Plugins
- Update Plugin-Config

**Comment by bamarc** [comment]
I have updated SDK, Gradle and version range inside the plugin config but IntelliJ still marks it as incompatible with 2022.2

Even the plugin checker veriefied it as compatible but the IDE itself will not allow to install it.

Very strange.

**Comment by astange1** [comment]
I just downloaded the 6.0.6 plugin and observe the same behavior where Intellij refuses to install it.   Just commenting to confirm that it's not just you for which this isn't working.
 Thank you for creating this version.

**Comment by bamarc** [comment]
Version 6.0.5 should still be compatible with 2022.2 and should now be installable via Marketplace. I have changed the version range inside the marketplace manually.

**Comment by astange1** [comment]
Thank you for your quick response.    We are behind a secure environment so plugin installation is a manual process.   I just manually downloaded the 6.0.5 plugin version and then attempted to install it in the 2022.2.   I received a dialog box stating that 6.0.5 was explicitly marked as incompatible with the current version of the IDE.     I'm running 222.3345.118.

**Comment by bamarc** [comment]
I have compiled you a Version 6.0.6 with a plugin version range of 221.* to 223.*, this should be able to install in 2022.2 without warnings. 

[WicketForge-6.0.6.zip](https://github.com/wicketforge/wicketforge/files/9260955/WicketForge-6.0.6.zip)

Seems like they either forgot to update the platform version number inside IntelliJ or have a bug inside their compatibility checker.

**Comment by astange1** [comment]
I don't usually accept code from strangers on the internet, but I will give this a try.   Thank you @bamarc

**Comment by astange1** [comment]
That worked.   Thank you.

**Comment by bamarc** [comment]
I've published a hotfix version 6.0.6.1 which fixes the problem by changing the version range. This should solve this issue until Jetbrains fixes the plugin verifier.
