### ISSUE TITLE
Add support for IDEA 2024.1

### ISSUE THREAD

**Issue by nukul4r** [wicketforge/wicketforge#196]
The version is currently in EAP. When opening IDEA, the following error is shown:

![image](https://github.com/wicketforge/wicketforge/assets/5287555/60117563-d0d4-4d55-a756-3afdbf76022a)

Thanks!

**Comment by bamarc** [comment]
I added preliminary support for 2024.1  in the EAP channel, you can find i either [here](https://github.com/wicketforge/wicketforge/releases/tag/6.0.10-eap) or in the [jetbrains marketplace](https://plugins.jetbrains.com/plugin/1545-wicketforge/edit/versions/eap)

**Comment by bamarc** [comment]
Intellij 2024.1 is now live so I will upload a version to the stable channel sometime today.
Until then you can just use the EAP Version and update once the new version is available.

**Comment by bamarc** [comment]
New version should now be live, please open a ticket if something is not working as before.
